[package]
name = "owntracks-duck-tape"
version = "0.1.0"
edition = "2021"

[features]
bundled = ["duckdb/bundled"]

[dependencies]
dotenvy = "0.15.7"
duckdb = "1.1.1"
rumqttc = { version = "0.24.0", features = ["url"] }
