[package]
name = "owntracks-duck-tape"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "OwnTracks DuckDB Recorder"
authors = ["Pirmin Kalberer <pirmin.kalberer@gmail.com>"]
license = "AGPL3"

[features]
bundled = ["duckdb/bundled"]

[dependencies]
anyhow = "1.0.95"
dotenvy = "0.15.7"
duckdb = "1.1.1"
env_logger = "0.11.6"
log = "0.4.22"
rumqttc = { version = "0.24.0", features = ["url"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
